# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.proto.distance.v1 import distance_pb2 as proto_dot_distance_dot_v1_dot_distance__pb2


class DistanceServiceStub(object):
    """DistanceService provides operations for calculating distance-from-home metrics
    using OwnTracks GPS data from a PostgreSQL database.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateDistanceFromHome = channel.unary_unary(
                '/distance.v1.DistanceService/CalculateDistanceFromHome',
                request_serializer=proto_dot_distance_dot_v1_dot_distance__pb2.CalculateDistanceRequest.SerializeToString,
                response_deserializer=proto_dot_distance_dot_v1_dot_distance__pb2.CalculateDistanceResponse.FromString,
                )
        self.GetJobStatus = channel.unary_unary(
                '/distance.v1.DistanceService/GetJobStatus',
                request_serializer=proto_dot_distance_dot_v1_dot_distance__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=proto_dot_distance_dot_v1_dot_distance__pb2.GetJobStatusResponse.FromString,
                )
        self.ListJobs = channel.unary_unary(
                '/distance.v1.DistanceService/ListJobs',
                request_serializer=proto_dot_distance_dot_v1_dot_distance__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=proto_dot_distance_dot_v1_dot_distance__pb2.ListJobsResponse.FromString,
                )


class DistanceServiceServicer(object):
    """DistanceService provides operations for calculating distance-from-home metrics
    using OwnTracks GPS data from a PostgreSQL database.
    """

    def CalculateDistanceFromHome(self, request, context):
        """CalculateDistanceFromHome initiates an async job to calculate distance metrics
        for a specific date from the fixed home location (40.736097°N, 74.039373°W).
        Returns a job ID for status polling and result retrieval.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """GetJobStatus returns the current status of a distance calculation job.
        Use this to poll for job completion and retrieve results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """ListJobs returns a list of distance calculation jobs with optional filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateDistanceFromHome': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateDistanceFromHome,
                    request_deserializer=proto_dot_distance_dot_v1_dot_distance__pb2.CalculateDistanceRequest.FromString,
                    response_serializer=proto_dot_distance_dot_v1_dot_distance__pb2.CalculateDistanceResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=proto_dot_distance_dot_v1_dot_distance__pb2.GetJobStatusRequest.FromString,
                    response_serializer=proto_dot_distance_dot_v1_dot_distance__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=proto_dot_distance_dot_v1_dot_distance__pb2.ListJobsRequest.FromString,
                    response_serializer=proto_dot_distance_dot_v1_dot_distance__pb2.ListJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distance.v1.DistanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DistanceService(object):
    """DistanceService provides operations for calculating distance-from-home metrics
    using OwnTracks GPS data from a PostgreSQL database.
    """

    @staticmethod
    def CalculateDistanceFromHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distance.v1.DistanceService/CalculateDistanceFromHome',
            proto_dot_distance_dot_v1_dot_distance__pb2.CalculateDistanceRequest.SerializeToString,
            proto_dot_distance_dot_v1_dot_distance__pb2.CalculateDistanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distance.v1.DistanceService/GetJobStatus',
            proto_dot_distance_dot_v1_dot_distance__pb2.GetJobStatusRequest.SerializeToString,
            proto_dot_distance_dot_v1_dot_distance__pb2.GetJobStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distance.v1.DistanceService/ListJobs',
            proto_dot_distance_dot_v1_dot_distance__pb2.ListJobsRequest.SerializeToString,
            proto_dot_distance_dot_v1_dot_distance__pb2.ListJobsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
