/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nested spans demonstration.
         * @description Demonstrates nested spans with simulated work across three steps:
         *     1. Database query (PostgreSQL)
         *     2. Cache lookup (Redis)
         *     3. External API call
         *
         *     Each step creates a child span with relevant attributes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chain operation completed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @example chain complete */
                            status?: string;
                            /**
                             * @example [
                             *       "db_query",
                             *       "cache_check",
                             *       "api_call"
                             *     ]
                             */
                            steps?: string[];
                            /** @example 0af7651916cd43dd8448eb211c80319c */
                            trace_id?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/db/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query owntracks locations.
         * @description Retrieves location records from the owntracks.locations table.
         *     Supports pagination, sorting, and filtering by device_id.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Maximum number of records to return (max 100)
                     * @example 10
                     */
                    limit?: number;
                    /**
                     * @description Number of records to skip for pagination
                     * @example 0
                     */
                    offset?: number;
                    /**
                     * @description Column to sort by
                     * @example created_at
                     */
                    sort?: "created_at" | "latitude" | "longitude" | "accuracy" | "altitude" | "velocity" | "battery";
                    /**
                     * @description Sort order
                     * @example desc
                     */
                    order?: "asc" | "desc";
                    /**
                     * @description Filter by device identifier
                     * @example iphone
                     */
                    device_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Location records */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @example 10 */
                            count?: number;
                            /** @example 20 */
                            limit?: number;
                            locations?: {
                                /** @description Accuracy in meters */
                                accuracy?: number;
                                /** @description Altitude in meters */
                                altitude?: number;
                                /** @description Battery percentage */
                                battery?: number;
                                /** Format: datetime */
                                created_at?: string;
                                /** @description Device identifier */
                                device_id?: string;
                                id?: number;
                                /** Format: float */
                                latitude?: number;
                                /** Format: float */
                                longitude?: number;
                                /** @description Tracker ID */
                                tid?: string;
                                /** @description Velocity in km/h */
                                velocity?: number;
                            }[];
                            /** @example 0 */
                            offset?: number;
                            /** @example desc */
                            order?: string;
                            /** @example created_at */
                            sort?: string;
                            trace_id?: string;
                        };
                    };
                };
                /** @description Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Database query failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/db/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database connection status.
         * @description Tests the connection to PostgreSQL via PgBouncer and returns connection info.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Database connection successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @example owntracks */
                            database?: string;
                            /** @example 192.168.1.175 */
                            host?: string;
                            /** @example 6432 */
                            port?: number;
                            /** @example 140005 */
                            server_version?: string;
                            /** @example connected */
                            status?: string;
                            trace_id?: string;
                        };
                    };
                };
                /** @description Database connection failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/error": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Error recording demonstration.
         * @description Demonstrates how errors are recorded in OpenTelemetry traces.
         *     This endpoint intentionally raises an exception to show error handling.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Simulated error response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @example Simulated error for tracing demo */
                            message?: string;
                            /** @example error */
                            status?: string;
                            /** @example 0af7651916cd43dd8448eb211c80319c */
                            trace_id?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files or read file content.
         * @description If path is a directory, returns a list of files and subdirectories.
         *     If path is a file, returns the file content.
         *     Supports nested paths like `/files/subdir/file.txt`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Path to file or directory (relative to storage root) */
                    filepath: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Directory listing or file content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @description Only present for files */
                            content?: string;
                            /** @description Only present for directories */
                            items?: {
                                name?: string;
                                size?: number;
                                /** @enum {string} */
                                type?: "file" | "directory";
                            }[];
                            /** @example subdir */
                            path?: string;
                            /** @description File size in bytes (only for files) */
                            size?: number;
                            trace_id?: string;
                            /**
                             * @example directory
                             * @enum {string}
                             */
                            type?: "directory" | "file";
                        };
                    };
                };
                /** @description Invalid path (path traversal attempt) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Path not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a new directory.
         * @description Creates a new directory. Parent directories are created if needed.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Directory path to create
                         * @example subdir/newdir
                         */
                        path: string;
                    };
                };
            };
            responses: {
                /** @description Directory already exists */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Directory created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            path?: string;
                            /** @example created */
                            status?: string;
                            trace_id?: string;
                            /** @example directory */
                            type?: string;
                        };
                    };
                };
                /** @description Invalid path or missing path parameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files or read file content.
         * @description If path is a directory, returns a list of files and subdirectories.
         *     If path is a file, returns the file content.
         *     Supports nested paths like `/files/subdir/file.txt`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Path to file or directory (relative to storage root) */
                    filepath: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Directory listing or file content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @description Only present for files */
                            content?: string;
                            /** @description Only present for directories */
                            items?: {
                                name?: string;
                                size?: number;
                                /** @enum {string} */
                                type?: "file" | "directory";
                            }[];
                            /** @example subdir */
                            path?: string;
                            /** @description File size in bytes (only for files) */
                            size?: number;
                            trace_id?: string;
                            /**
                             * @example directory
                             * @enum {string}
                             */
                            type?: "directory" | "file";
                        };
                    };
                };
                /** @description Invalid path (path traversal attempt) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Path not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{filepath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files or read file content.
         * @description If path is a directory, returns a list of files and subdirectories.
         *     If path is a file, returns the file content.
         *     Supports nested paths like `/files/subdir/file.txt`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Path to file or directory (relative to storage root) */
                    filepath: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Directory listing or file content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @description Only present for files */
                            content?: string;
                            /** @description Only present for directories */
                            items?: {
                                name?: string;
                                size?: number;
                                /** @enum {string} */
                                type?: "file" | "directory";
                            }[];
                            /** @example subdir */
                            path?: string;
                            /** @description File size in bytes (only for files) */
                            size?: number;
                            trace_id?: string;
                            /**
                             * @example directory
                             * @enum {string}
                             */
                            type?: "directory" | "file";
                        };
                    };
                };
                /** @description Invalid path (path traversal attempt) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Path not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Write content to a file.
         * @description Writes content to a file. Creates parent directories if they don't exist.
         *     Content should be sent as the request body (text/plain or application/json with "content" field).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Path to the file (relative to storage root) */
                    filepath: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Body"];
            responses: {
                /** @description File updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            path?: string;
                            size?: number;
                            /** @example updated */
                            status?: string;
                            trace_id?: string;
                        };
                    };
                };
                /** @description File created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            path?: string;
                            size?: number;
                            /** @example created */
                            status?: string;
                            trace_id?: string;
                        };
                    };
                };
                /** @description Invalid path or missing content */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Write content to a file.
         * @description Writes content to a file. Creates parent directories if they don't exist.
         *     Content should be sent as the request body (text/plain or application/json with "content" field).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Path to the file (relative to storage root) */
                    filepath: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["Body"];
            responses: {
                /** @description File updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            path?: string;
                            size?: number;
                            /** @example updated */
                            status?: string;
                            trace_id?: string;
                        };
                    };
                };
                /** @description File created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            path?: string;
                            size?: number;
                            /** @example created */
                            status?: string;
                            trace_id?: string;
                        };
                    };
                };
                /** @description Invalid path or missing content */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Delete a file or empty directory.
         * @description Deletes a file or an empty directory.
         *     Non-empty directories cannot be deleted (returns 400).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Path to the file or directory to delete */
                    filepath: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File or directory deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            path?: string;
                            /** @example deleted */
                            status?: string;
                            trace_id?: string;
                            /** @enum {string} */
                            type?: "file" | "directory";
                        };
                    };
                };
                /** @description Invalid path or directory not empty */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Path not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint.
         * @description Returns the health status of the application. Used by Kubernetes liveness probes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Application is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @example healthy */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service info endpoint.
         * @description Returns service information including version, build info, and a trace ID for verification in New Relic.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service information with trace ID */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @example 2026-01-13T18:00:00Z */
                            build_date?: string;
                            /** @example 42 */
                            build_number?: string;
                            /** @example OpenTelemetry Demo App - Traces flowing to New Relic! */
                            message?: string;
                            /** @example https://one.newrelic.com/distributed-tracing?query=trace.id%3D... */
                            new_relic_url?: string;
                            /** @example otel-demo */
                            service?: string;
                            /** @example 0af7651916cd43dd8448eb211c80319c */
                            trace_id?: string;
                            /** @example 1.0.42 */
                            version?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observability configuration info.
         * @description Returns the current OpenTelemetry configuration and available endpoints.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Observability configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            endpoints?: {
                                [key: string]: string;
                            };
                            /** @example homelab */
                            environment?: string;
                            /** @example localhost:4317 */
                            otel_endpoint?: string;
                            /** @example otel-demo */
                            service_name?: string;
                            /** @example otel-demo */
                            service_namespace?: string;
                            /** @example 1.0.0 */
                            version?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check endpoint.
         * @description Returns the readiness status of the application. Used by Kubernetes readiness probes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Application is ready to receive traffic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /** @example ready */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slow operation demonstration.
         * @description Demonstrates a slow operation with a random delay between 0.5 and 2.0 seconds.
         *     Useful for testing latency monitoring and performance analysis in traces.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Slow operation completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": {
                            /**
                             * Format: float
                             * @example 1.23
                             */
                            delay_seconds?: number;
                            /** @example complete */
                            status?: string;
                            /** @example 0af7651916cd43dd8448eb211c80319c */
                            trace_id?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description File content (plain text or JSON with "content" field) */
        Body: {
            content: {
                "application/json": {
                    /** @example Hello, World! */
                    content?: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
